"""empty message

Revision ID: 92f98f1b6180
Revises: 2313b4166d63
Create Date: 2024-02-09 13:15:57.131705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f98f1b6180'
down_revision = '2313b4166d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_cat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sub_cat')

    # ### end Alembic commands ###
